### ISSUE TITLE
Link to mono version is broken

### ISSUE THREAD

**Issue by riban-bw** [brummer10/ImpulseLoaderStereo.lv2#2]
In the README there is a link to the mono version but that link is broken.

A Mono version of ImpulseLoaderStereo is here [ImpulseLoader](https://raw.githubusercontent.com/brummer10/ImpulseLoader.lv2)

**Comment by riban-bw** [comment]
Should be `https://github.com/brummer10/ImpulseLoader.lv2`, not `https://raw.githubusercontent.com/brummer10/ImpulseLoader.lv2`.

**Comment by brummer10** [comment]
Thanks for head up, should be fixed now.
